#
#    This file is part of the Pi Entertainment System (PES).
#
#    PES provides an interactive GUI for games console emulators
#    and is designed to work on the Raspberry Pi.
#
#    Copyright (C) 2020 Neil Munday (neil@mundayweb.com)
#
#    PES is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    PES is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with PES.  If not, see <http://www.gnu.org/licenses/>.
#

---
- name: "install packages"
  pacman:
    state: present
    name:
      - alsa-utils
      - autoconf
      - automake
      - bison
      - byacc
      - dhcpcd
      - dosfstools
      - fakeroot
      - flex
      - gcc
      - cmake
      - crda
      - iw
      - kodi-platform
      - kodi-rbp
      - kodi-rbp-dev
      - kodi-rbp-eventclients
      - kodi-rbp-tools-texturepacker
      - make
      - mesa
      - mesa-libgl
      - mc
      - p7zip
      - patch
      - pkg-config
      - rsync
      - samba
      - scons
      - screen
      - sudo
      - swig
      - unzip
      - vim
      - wget
      - wpa_supplicant
      - xa
      - zip
